// generated by chatgpt

const getCombinations = (arr, k) => {
  const results = [];

  const combine = (start, combo) => {
    if (combo.length === k) {
      // 기저 사례: 현재 조합의 길이가 k와 같으면
      results.push([...combo]); // 현재 조합을 결과 배열에 추가
      return;
    }
    for (let i = start; i < arr.length; i++) {
      combo.push(arr[i]); // 현재 요소를 조합에 추가
      combine(i + 1, combo); // 재귀 호출: 다음 요소로 이동
      combo.pop(); // 현재 요소를 조합에서 제거하여 백트래킹
    }
  };

  combine(3, []); // 초기 호출: 시작 인덱스 0과 빈 조합으로 시작
  console.log(result);
  return results; // 모든 조합을 반환
};
